@startuml

class Game {
  state: GameState
  region: string
  oppositionId: number
}

class Dungeon {
  name: string
}

class Fight {
  round: number
}


class Party {
}

class PartyRow {
}

class Opposition {
}

class OppositionRow {
}

class TurnOrder {
}

class Creature {
  type : CreatureType
  name : string
  lifeMax : number
  life : number
}

class Character {
  level: number
  useMana: boolean
}

class Enemy {
  baseName: string
  actions: number
}

class EnemyStrategy {
}

class SingleSkillStrategy {
}

class Skill {
  type: SkillIconType
  name: string
  targetType: SkillTargetType
  cost: number
  range: number
  cooldownMax: number
  cooldown: number
  description: string
  powerLevels: number[]
  status: StatusType
  improvementStatus: boolean
}

Game *-- Party
Game *-- Fight
Game *-- "*" Dungeon
Game *-- Dungeon
Dungeon *-- "*" Opposition
Fight -- Party
Fight -- Opposition
Fight *-- TurnOrder
Fight *-- Creature : "Active\ncreature"
Fight *-- "*" Creature : "Target\ncreatures"
TurnOrder o-- "*" Creature
Party *-- "*" PartyRow
PartyRow *-- "*" Character
Opposition *-- "*" OppositionRow
OppositionRow *-- "*" Enemy
Creature <|-- Character
Character *-- "*" Skill
Enemy *-- EnemyStrategy
Creature <|-- Enemy
EnemyStrategy <|-- SingleSkillStrategy
SingleSkillStrategy -right- Skill

@enduml
